"""
GroWDash — Core API Gateway
============================

This module serves as the primary entry point and orchestrator for the GroWDash
FastAPI backend service. It bridges the gap between the React-based frontend
dashboard and the external Growatt server infrastructure.

Key Responsibilities:
---------------------
1. **Application Initialization**: Bootstraps the FastAPI instance with project
   metadata including title, description and version for OpenAPI documentation.

2. **Rate Limiting**: Registers a global slowapi Limiter instance on the
   application state, enabling per-endpoint rate limiting across all routers.
   The RateLimitExceeded exception handler ensures clients receive a well-formed
   HTTP 429 response rather than an unhandled 500 error.

3. **CORS Configuration**: Establishes Cross-Origin Resource Sharing policies
   to allow the React frontend to communicate with the API across different
   origins during both local development and production deployments.

4. **Router Delegation**: Mounts domain-specific route handlers for authentication,
   plant metadata, energy data and device telemetry under a unified app instance.

5. **Health Monitoring**: Exposes a lightweight root endpoint for container
   liveness probes and connectivity verification.

Architecture Notes:
-------------------
The Limiter instance defined here is shared with the routers via app.state.limiter.
Individual route handlers in routers (e.g., auth.py) define their own Limiter
instance with the same key_func — slowapi resolves the active limiter at request
time from app.state, so the router-level instance is used only for the decorator
syntax. Both must use the same key_func (get_remote_address) for consistent behavior.

Cloudflare Tunnel Note:
-----------------------
When deployed behind a Cloudflare Tunnel, the client IP seen by FastAPI may
be the tunnel's internal address rather than the real client IP. If rate limiting
by real IP is required, configure get_remote_address to read the X-Forwarded-For
header, or replace it with a custom key function in both this file and auth.py.

Usage:
------
Launch the development server with live-reloading:
    $ uvicorn main:app --reload

Interactive API documentation (auto-generated by FastAPI):
    Swagger UI: http://127.0.0.1:8000/docs
    ReDoc:      http://127.0.0.1:8000/redoc
"""

from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from routers import plant, energy, device, auth, weather
import models
from database import engine


# ---------------------------------------------------------------------------
# Rate Limiter
# ---------------------------------------------------------------------------
# Global Limiter instance registered on app.state so that slowapi can resolve
# it at request time across all routers. Uses the client's remote IP address
# as the rate limit key. Individual endpoints opt in via the @limiter.limit()
# decorator defined in their respective router modules.
limiter = Limiter(key_func=get_remote_address)


# ---------------------------------------------------------------------------
# Database Initialization
# ---------------------------------------------------------------------------
# Creates all tables defined in models.py (e.g., the users table) if they do
# not already exist. Safe to call on every startup — SQLAlchemy's create_all
# is idempotent and will not modify or drop existing tables.
models.Base.metadata.create_all(bind=engine)


# ---------------------------------------------------------------------------
# Application Instance
# ---------------------------------------------------------------------------
# These metadata fields are surfaced in the auto-generated OpenAPI schema and
# displayed prominently in the Swagger UI and ReDoc documentation pages.
app = FastAPI(
    title="GroWDash API",
    description="Comprehensive backend API driving your Growatt photovoltaic plant dashboard.",
    version="0.1.0",
)


# ---------------------------------------------------------------------------
# Rate Limiting Registration
# ---------------------------------------------------------------------------
# Attaches the limiter to the app state so slowapi can retrieve it during
# request processing. The exception handler converts RateLimitExceeded errors
# into properly formatted HTTP 429 Too Many Requests responses with a
# Retry-After header indicating when the client may retry.
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)


# ---------------------------------------------------------------------------
# CORS Middleware
# ---------------------------------------------------------------------------
# CORS is enforced by browsers to prevent unauthorized cross-origin requests.
# By default, a script at http://localhost:5173 is blocked from calling
# http://localhost:8000 unless the server explicitly permits it.
#
# allow_credentials=True is required for the HttpOnly cookie authentication
# flow — without it, browsers will not send or receive cookies on cross-origin
# requests regardless of the SameSite cookie attribute.
#
# Production note: replace the wildcard-style local origins with the specific
# Cloudflare domain once the tunnel is active, to avoid inadvertently allowing
# requests from other localhost services on the same machine.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",    # Vite dev server
        "http://127.0.0.1:5173",
        "http://localhost:8000",    # FastAPI self-reference (Swagger UI)
        "http://127.0.0.1:8000",
        "http://localhost",         # Docker / LAN access without port
        "http://127.0.0.1",
    ],
    allow_credentials=True,         # Required for HttpOnly cookie auth
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Router Registration
# ---------------------------------------------------------------------------
# Each router encapsulates a distinct domain of the API surface. Splitting
# routes across dedicated modules keeps each file focused and independently
# testable. All routers share the same app instance and middleware stack.
app.include_router(auth.router)     # POST /auth/token, POST /auth/logout, GET /auth/me
app.include_router(plant.router)    # GET  /plant/info
app.include_router(energy.router)   # GET  /energy/overview, /today, /history, /aggregate, /daily-breakdown
app.include_router(device.router)   # GET  /device/list, /detail, /settings
app.include_router(weather.router)  # GET  /weather/current, /solar-forecast



# ---------------------------------------------------------------------------
# Health Check
# ---------------------------------------------------------------------------
@app.get("/", summary="System Health Check", tags=["General"])
def root():
    """
    Root liveness endpoint for the GroWDash API.

    A lightweight probe that confirms the uvicorn process is running and
    the application has initialized successfully. Performs no database
    queries, external API calls or heavy computation.

    Intended consumers:
        - Docker / Kubernetes liveness and readiness probes.
        - Reverse proxies (Nginx, Traefik, Cloudflare) verifying upstream health.
        - Developers confirming the server bound to the expected port.

    Returns:
        dict: A static JSON payload confirming the service is operational.
              Example: {"message": "GroWDash API operates nominally and is ready to accept requests."}
    """
    return {"message": "GroWDash API operates nominally and is ready to accept requests."}