"""
GroWDash - Core API Gateway
===========================

This module serves as the primary entry point and orchestrator for the GroWDash 
FastAPI backend service. It bridges the gap between the React-based frontend 
dashboard and the external Growatt server infrastructure.

Key Responsibilities:
---------------------
1. **Application Initialization**: Bootstraps the FastAPI instance with project metadata.
2. **CORS Configuration**: Establishes secure Cross-Origin Resource Sharing policies 
   to allow seamless communication from development and production frontend origins.
3. **Router Delegation**: Systematically groups and mounts domain-specific route 
   handlers (Plants, Devices, Energy) to maintain a modular and scalable codebase.
4. **Health Monitoring**: Provides a lightweight root endpoint to rapidly verify 
   container and service vitality.

Usage Guide:
------------
To launch the development server with live-reloading enabled:
    $ uvicorn main:app --reload

To access the interactive, OpenAPI-compliant documentation automatically generated by FastAPI:
    - Swagger UI: http://127.0.0.1:8000/docs
    - ReDoc:      http://127.0.0.1:8000/redoc
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from routers import plant, energy, device, auth
import models
from database import engine

# Generate database tables (e.g., users table) on startup
models.Base.metadata.create_all(bind=engine)

# Initialize the core FastAPI application instance.
# These metadata fields (title, description, version) are prominently displayed 
# in the automatically generated OpenAPI / Swagger documentation pages.
app = FastAPI(
    title="GroWDash API",
    description="Comprehensive backend API driving your Growatt photovoltaic plant dashboard.",
    version="0.1.0",
)

# ---------------------------------------------------------
# CORS (Cross-Origin Resource Sharing) Configuration
# ---------------------------------------------------------
# CORS acts as a critical security feature implemented by modern web browsers.
# By default, a browser restricts scripts running on one origin (e.g., http://localhost:5173) 
# from interacting with resources from another origin (e.g., http://localhost:8000).
# We must explicitly whitelist the origins where our React frontend might be hosted.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Local Development: Default port for Vite React servers
        "http://localhost:80",     # Local Production: Default HTTP port for Docker + Nginx
        "http://localhost",        # Local Production: Implicit HTTP port for Docker + Nginx
    ],
    allow_credentials=True,        # Permits cookies, authorization headers, or TLS client certificates
    allow_methods=["*"],           # Whitelists all HTTP verbs (GET, POST, PUT, DELETE, OPTIONS, etc.)
    allow_headers=["*"],           # Whitelists all HTTP headers (Authorization, Content-Type, etc.)
)

# ---------------------------------------------------------
# Route Registration
# ---------------------------------------------------------
# By utilizing APIRouters, the application's endpoints are cleanly separated 
# into distinct files based on their domain context. This vastly improves 
# maintainability and team collaboration as the API surface grows.
app.include_router(auth.router)    # Authentication and token issuance
app.include_router(plant.router)   # Endpoints mapping to general PV Plant metadata
app.include_router(energy.router)  # Endpoints aggregating power generation and flow metrics
app.include_router(device.router)  # Endpoints fetching hardware states (Inverters, Dataloggers)


@app.get("/", summary="System Health Check", tags=["General"])
def root():
    """
    Root Health Check Endpoint
    
    This lightweight route acts as a heartbeat monitor for the FastAPI application.
    It performs no heavy computation or external API requests.
    
    Commonly utilized by:
    - Docker / Kubernetes liveness and readiness probes to ensure the container hasn't stalled.
    - Reverse proxies (like Nginx or Traefik) to verify upstream availability before routing traffic.
    - Developers for an immediate "sanity check" that the uvicorn process bound to the port correctly.
    
    Returns:
        dict: A statically defined JSON payload verifying the service is actively listening.
    """
    return {"message": "GroWDash API operates nominally and is ready to accept requests."}